# Generated by Django 4.1.4 on 2023-01-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Name')),
                ('duration', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('time_one', models.TimeField(db_index=True)),
                ('time_two', models.TimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api',
            },
        ),
    ]
